### PR TITLE
Restart of Brix CMS Plugins

### PR DESCRIPTION
**Pull request by dsimko**
First of all I am really sorry for this **huge** PR. It is mainly about:

- removing obsolete modules
-- brix-plugin-article
-- brix-plugin-file
-- brix-plugin-gallery
-- examples
-- security
- adding new plugin (brix-plugin-content) + demo
-- it is not finished yet there is a lot of features which I would like to implement
-- online demo is here: http://46.183.65.66:8080/blog.html
-- plugin manage its own workspace so if you want to see admin part you have to switch workspace
- upgrage and refactoring of brix-hierarchical-node-plugin in order to preserve brix-plugin convention

### CODE REVIEW

**Comment by kbachl** [comment]
Hi Dan,

good to see you're already sorry for the size ;) 

I've looked at the demo and it looks amazing! - Only 1 thing is a real problem, as you write:

> plugin manage its own workspace so if you want to see admin part you have to switch workspace

This is somewhat a problem; Brix usually should only use 1 (!) workspace for all content of the specific site, reason is that only this way export/ import and the publish plugin can work; I - for example - use the publish plugin, so we have 3 workspaces: production, test, development and this only works when all data is in exactly 1 workspace; Plus, brix is made to be able to power multiple domains at the same time using different workspaces: having 1 workspace for the content alo collides there;
Another problem is the referential integrity in case you later want to reference a node in a blog content as you cant reference overworkspaces reliable...

What you should do here is just another sub-root node from type e.g.: Plugin.ContentBlog and have all this shown in a different tab at the same workspace; IMHO

WDYT?

**Comment by dsimko** [comment]
> This is somewhat a problem; Brix usually should only use 1 (!) workspace for all content of the specific site, reason is that only this way export/ import and the publish plugin can work;

I don't agree. There is a lot of reasons for which is better to have seperate workspace for site and for data. e.g.  you can have many gigabytes in photo galleries and I don't want this mess in site workspace. Another thing is that I don't want to mix publish rights for site workspace and publish rights for content workspace - these are very different rights. And export / import works for each workspace separately.

>for example - use the publish plugin, so we have 3 workspaces: production, test, development and this only works when all data is in exactly 1 workspace;

No, it works for each workspace separately. Content redactor / publisher is not site administrator.

>Plus, brix is made to be able to power multiple domains at the same time using different workspaces: having 1 workspace for the content alo collides there;

Again I don't agree. Having multiple domains have nothing common with having separate workspace for data.

>Another problem is the referential integrity in case you later want to reference a node in a blog content as you cant reference overworkspaces reliable...

I don't see any reason why you should need a reference to site node. You always can use workspace name + path.

>What you should do here is just another sub-root node from type e.g.: Plugin.ContentBlog and have all this shown in a different tab at the same workspace; IMHO

This was my first implementation many years ago but the need for something more robust came quite quickly. But if you really think that it is necessary to have everything in one workspace it shouldn't be difficult to add some config option.

**Comment by kbachl** [comment]
> I don't agree. There is a lot of reasons for which is better to have seperate workspace for site and for data. e.g. you can have many gigabytes in photo galleries and I don't want this mess in site workspace. Another thing is that I don't want to mix publish rights for site workspace and publish rights for content workspace - these are very different rights. And export / import works for each workspace separately.

Well, then at least make the naming scheme of the workspace to a child of the brix workspace, e.g: 
BrixWorkspaceName = MySite
Content = MySite.ContenPlugin
FooBar(later) MySite.FooBar

that way there is no need to "tie" or "define" the containing workspace (so less config needed in the tile - and all config can break at one point) and export/ import/ snapshoting etc. can be made working with that later on, as the function could be enhanced that subworkspaces (e.g.: the ones having workspaceName. in them) get handled on the fly and also allowing to make more plugins with different workspaces... even some meta ones;

> Again I don't agree. Having multiple domains have nothing common with having separate workspace for data.

It has because in the current state we have a mess of workspace naming.... 

> I don't see any reason why you should need a reference to site node. You always can use workspace name + path.

Well, the idea behind brix and all its parts is that menus, links etc. use a Reference to get the target of the href; that way a page can be moved and/ or renamed and all links on page are still working; That reference works using the reference of the JCR and this also can be used to make sure nothing gets deleted as long as its "connected" on the site... you can abandon that and use plain text for any links, but you lose the functionality then

>This was my first implementation many years ago but the need for something more robust came quite quickly. But if you really think that it is necessary to have everything in one workspace it shouldn't be difficult to add some config option.

I'm against multiple options: have it one way, and make this the *right*-way

**Comment by dsimko** [comment]
> Well, then at least make the naming scheme of the workspace to a child of the brix workspace, e.g:
BrixWorkspaceName = MySite
Content = MySite.ContenPlugin
FooBar(later) = MySite.FooBar

I like that idea! I can't find any use case where one 'content workspace' could be used by more sites. So I am going to change this.

**Comment by kbachl** [comment]
Ok, I've made https://github.com/brix-cms/brix-cms/issues/196 and I think this might be a cool feature for the future as it allows content decoupling - however, there might be strange sideeffects if we really go the way I pointed out under "To Discuss for the Future:"

**Comment by dsimko** [comment]
Name of the content workspace ends with ".ContenPlugin" now. Online demo also updated.

**Pull request merged**
