### PR TITLE
added two new plugins and improved demo application

### PR DESCRIPTION
**Pull request by dsimko**
Another huge PR (sorry, this should be the last) which adds 2 new plugins:
- brix-plugin-jpa it is like brix-plugin-hierarchical-node but for jpa entities
- brix-plugin-usermgmt for management of users and roles (not finished yet)

brix-plugin-content-demo renamed to brix-plugins-demo and switched to Spring boot. You can try to login as editor or admin http://46.183.65.66:8080

### CODE REVIEW

**Comment by kbachl** [comment]
I really must say I'm quite impressed with what you've done so far... I looked at the demo and it gets better and better... only problem was that some idiot (the same one that is writing these lines!) deleted the admin from the user management and somehow got locked out :blush: 

I find the idea of an empedded, simple user management really good. Did you do the JPA purely for this or do you have some "larger" plan behind?

oh and btw: maybe we shouldnt allow the last admin to delete himself.... :baby_symbol:

**Comment by dsimko** [comment]
> I really must say I'm quite impressed with what you've done so far... I looked at the demo and it gets better and better...

Thank you :)

> only problem was that some idiot (the same one that is writing these lines!) deleted the admin from the user management and somehow got locked out 😊

no problem, I have just restarted demo

> I find the idea of an empedded, simple user management really good. Did you do the JPA purely for this or do you have some "larger" plan behind?

User management is not the only reason. it's supposed to be a framework for any jpa entities or it could be even more general and useful for Mongo documents and etc..  

> oh and btw: maybe we shouldnt allow the last admin to delete himself.... 🚼

Yes, I was thinking about that. I'll improve the demo later.

**Comment by kbachl** [comment]
> no problem, I have just restarted demo

thx a lot :) 

btw: how is your experience with spring boot? I looked at it and I could imagine it for demo's and similar but to power a big, long living webapp? - I somehow dont trust these single jar deployments... I'm still more pro appserver like payara or wildfly (or maybe I'm just getting too old) as running an webapp is usually more work than deploying it

**Comment by dsimko** [comment]
> btw: how is your experience with spring boot? I looked at it and I could imagine it for demo's and similar but to power a big, long living webapp? - I somehow dont trust these single jar deployments... I'm still more pro appserver like payara or wildfly (or maybe I'm just getting too old) as running an webapp is usually more work than deploying it

I enjoy working with Spring boot because I don't have to write almost none boilerplate code and when I need to integrate some third party technology (e.g. MongoDB) Spring and Spring Data is usually the best choice. And using Spring boot doesn't mean that you can't build your app as war and deploy it to the JEE app server (e.g. Wildfly).

**Pull request merged**
